version: "3.9"

services:
  nginx:
    image: nginx:1.19
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx

  php:
    build: ./php
    volumes:
      - ./app:/var/www/html
      - ./php/logs:/var/log
      - ./php/conf:/usr/local/etc/php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql

